// calendar actions
export const SET_DATE_ARRIVAL = 'SET_DATE_ARRIVAL'
export const SET_DATE_DEPARTURE = 'SET_DATE_DEPARTURE'
export const RESET_ALL_CALENDAR_DATE = 'RESET_ALL_CALENDAR_DATE'

export const RECEIVE_HOUSES_REQUEST = 'RECEIVE_HOUSES_REQUEST'
export const RECEIVE_HOUSES_SUCCESS = 'RECEIVE_HOUSES_SUCCESS'
export const RECEIVE_HOUSES_FAILURE = 'RECEIVE_HOUSES_FAILURE'
