// calendar actions
export const SET_NAME_OF_MONTH = 'SET_NAME_OF_MONTH'
export const SET_DATE = 'SET_DATE'
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE'
export const SET_CALENDAR_BODY = 'SET_CALENDAR_BODY'
export const RESET_ALL_CALENDAR_DATA = 'RESET_ALL_CALENDAR_DATA'
